tag1quo.settings:
  type: mapping
  label: 'Tag1 Quo Settings'
  mapping:
    api:
      type: mapping
      label: 'Tag1 Quo API Settings'
      mapping:
        baseUri:
          type: string
          label: 'API Base URI'
        endpoint:
          type: string
          label: 'API Endpoint'
        token:
          type: string
          label: 'API Token'
        version:
          type: string
          label: 'API Version'
    debug:
      type: mapping
      label: 'Tag1 Quo Debug Settings'
      mapping:
        enabled:
          type: boolean
          label: 'Enabled'
        xdebug:
          type: mapping
          label: 'Tag1 Quo Xdebug Settings'
          mapping:
            session:
              type: 'string'
              label: 'Xdebug Session'
    curl:
      type: mapping
      label: 'Tag1 Quo cURL'
      mapping:
        enabled:
          type: boolean
          label: 'Enabled'
        options:
          type: sequence
          label: 'Tag1 Quo cURL Options'
          sequence:
            type: tag1quo.settings.curl.options.[%key]
    enabled:
      type: boolean
      label: 'Enabled'
